release: add check for gh auth status
sourcegraph/deploy-sourcegraph-helm pull request #455
Opened 2024-04-23 14:58 UTC by BolajiOlajide

### Checklist

- [ ] Follow the [manual testing process](https://github.com/sourcegraph/deploy-sourcegraph-helm/blob/main/TEST.md)
- [ ] Update [changelog](https://github.com/sourcegraph/deploy-sourcegraph-helm/blob/main/charts/sourcegraph/CHANGELOG.md)
- [ ] Update [Kubernetes update doc](https://docs.sourcegraph.com/admin/updates/kubernetes)

### Test plan

Add step to check that release captain is authenticated via `gh` during the release process.

2024-04-23 17:02 UTC, jdpleiness approved these changes
Nice!

2024-04-23 18:33 UTC, DaedalusG approved these changes
Nice I believe @Chickensoupwithrice ran into this

2024-04-24 10:17 UTC, jhchabran requested changes

2024-04-24 10:17 UTC, jhchabran commented on release.yaml
> +              gh auth status
I think we should instead move this to the `requirements` and instead call `checkDeps` in `(*releaseRunner) Test(context.Context) error`. The repetition here is very error prone.

2024-04-24 10:22 UTC, jhchabran commented on release.yaml
> +              gh auth status
https://github.com/sourcegraph/sourcegraph/pull/62143

2024-04-24 16:32 UTC, jhchabran approved these changes
LGTM, I'll fix the part where we need to run this in the tests, over https://github.com/sourcegraph/sourcegraph/pull/62143

2024-04-24 16:35 UTC, merged