Refactor postgres reference
sourcegraph/deploy-sourcegraph-helm pull request #57
Opened 2022-03-02 08:02 UTC by david-sandy

Using latest tag, but, only tag available is very old.

2022-03-04 03:03 UTC, michaellzc requested changes
we usually only release changes to images and services during the monthly release or patch release.

we release new features to `helm` outside of the monthly release schedule, but we don't change any underlying images.

@caugustus-sourcegraph maybe we should leave this PR open until `3.38` release? Also, we need to figure out a process for `helm` to address changes like this in between monthly releases.

2022-03-04 03:03 UTC, michaellzc commented on charts/sourcegraph/values.yaml
> +    name: "postgres-12-alpine"
We use the comments like the inline comments to document these values and autogen our docs

```
# -- Docker image tag for the `pgsql` image
```

Would you add them back?

2022-03-04 16:17 UTC, caugustus-sourcegraph commented
@michaellzc - Hm, good point about the process. I wonder if the release tooling / batch changes supports adding onto an existing branch, instead of creating a new one. If it does, we could put changes like this on the publish branch so they're not picked up until the release.

For now, I agree that leaving the PR open is the best bet, and we'll merge it in right before the release? 🤷

2022-03-17 17:58 UTC, michaellzc commented
> @caugustus-sourcegraph @michaellzc I'm assuming that this just needs to be merged before the release tomorrow, and not the release cut today. Is that correct?

https://github.com/sourcegraph/sourcegraph/issues/31768

at this step `From the [release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes), merge the release-publishing PRs created previously.`, the release tool will create a batch change that includes a PR to this repository to bump images tags and chart version.

I would just merge these two release-blocker PRs __BEFORE__ you run the `yarn release release:stage` command

2022-03-18 12:24 UTC, caugustus-sourcegraph approved these changes

2022-03-18 12:26 UTC, merged